# Generated by Django 2.1.3 on 2018-12-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='ratings',
            field=models.CharField(max_length=1),
        ),
    ]
