# Generated by Django 2.1.3 on 2019-01-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181231_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='average',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
