# Generated by Django 2.1.3 on 2019-01-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='average',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
