# Generated by Django 2.1.3 on 2019-02-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190201_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
