# Generated by Django 2.1.3 on 2019-02-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_capsule_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Capsule')),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='playlistorder',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Playlist'),
        ),
    ]
