"""
Django settings for cpop_server project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zlo&3z^)pdi%z5dxgfvonsf(mgzy#&h(j#1q+%)j8cn7jbnih6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['serveur.plateforme.lepoles.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'api',
    'rest_framework.authtoken',
    'rest_framework',
    'djoser',
    'corsheaders',
    'rest_framework_swagger',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cpop_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
}

WSGI_APPLICATION = 'cpop_server.wsgi.application'



DATABASES = {
  'default': {
      'ENGINE': 'django.db.backends.postgresql',
      'NAME': 'v2commonspop',
      'USER': 'v2cpopuser',
      'PASSWORD': 'v2cpoppass',
      'HOST': '127.0.0.1',
      'PORT': '5432',
  }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'CET'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

DOMAIN = 'plateforme.lepoles.com'
#FRONT_URL = 'http://commonspopv2.lepoles.com'

EMAIL_HOST = 'SMTP.Office365.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'CommonsPops@lepoles.org'
DEFAULT_FROM_EMAIL = 'CommonsPops@lepoles.org'
EMAIL_FROM = 'CommonsPops@lepoles.org'
EMAIL_HOST_PASSWORD = 'Foh63976'
EMAIL_USE_TLS = True

DJOSER = {
    'DOMAIN': DOMAIN,
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',

}

#---------------------AWS----------------------
AWS_ACCESS_KEY_ID = 'AKIAJ3G7NPBCQ3JLMSZQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'projetpoppart'
AWS_S3_CUSTOM_DOMAIN = 'd16gc1wdsdgw9o.cloudfront.net'

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=31536000',
}

AWS_LOCATION = 'static'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)

DEFAULT_FILE_STORAGE = 'api.storage_backends.MediaStorage'
